<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdUsersLog', 'slave');

/**
 * BaseAdUsersLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_name
 * @property string $error_code
 * @property string $error_desc
 * @property string $content
 * @property timestamp $datetime
 * 
 * @method string     getUserName()   Returns the current record's "user_name" value
 * @method string     getErrorCode()  Returns the current record's "error_code" value
 * @method string     getErrorDesc()  Returns the current record's "error_desc" value
 * @method string     getContent()    Returns the current record's "content" value
 * @method timestamp  getDatetime()   Returns the current record's "datetime" value
 * @method AdUsersLog setUserName()   Sets the current record's "user_name" value
 * @method AdUsersLog setErrorCode()  Sets the current record's "error_code" value
 * @method AdUsersLog setErrorDesc()  Sets the current record's "error_desc" value
 * @method AdUsersLog setContent()    Sets the current record's "content" value
 * @method AdUsersLog setDatetime()   Sets the current record's "datetime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdUsersLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_users_log');
        $this->hasColumn('user_name', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Tài khoản của người dùng front end',
             'length' => 25,
             ));
        $this->hasColumn('error_code', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mã lỗi',
             'length' => 255,
             ));
        $this->hasColumn('error_desc', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mô tả lỗi',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 500, array(
             'type' => 'string',
             'comment' => 'Nội dung ghi log',
             'length' => 500,
             ));
        $this->hasColumn('datetime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'Thời gian ghi log',
             'length' => 25,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}