<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_tacpham', 'slave');

/**
 * Basecsdl_tacpham
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hoivien_id
 * @property string $tentacpham
 * @property string $gioithieu
 * @property string $anhdaidien
 * @property boolean $tacphamtieubieu
 * @property string $filedownload
 * @property timestamp $ngayxuatban
 * @property integer $tacgia_id
 * @property string $tacgia
 * @property integer $chude_id
 * @property integer $status
 * 
 * @method integer      getHoivienId()       Returns the current record's "hoivien_id" value
 * @method string       getTentacpham()      Returns the current record's "tentacpham" value
 * @method string       getGioithieu()       Returns the current record's "gioithieu" value
 * @method string       getAnhdaidien()      Returns the current record's "anhdaidien" value
 * @method boolean      getTacphamtieubieu() Returns the current record's "tacphamtieubieu" value
 * @method string       getFiledownload()    Returns the current record's "filedownload" value
 * @method timestamp    getNgayxuatban()     Returns the current record's "ngayxuatban" value
 * @method integer      getTacgiaId()        Returns the current record's "tacgia_id" value
 * @method string       getTacgia()          Returns the current record's "tacgia" value
 * @method integer      getChudeId()         Returns the current record's "chude_id" value
 * @method integer      getStatus()          Returns the current record's "status" value
 * @method csdl_tacpham setHoivienId()       Sets the current record's "hoivien_id" value
 * @method csdl_tacpham setTentacpham()      Sets the current record's "tentacpham" value
 * @method csdl_tacpham setGioithieu()       Sets the current record's "gioithieu" value
 * @method csdl_tacpham setAnhdaidien()      Sets the current record's "anhdaidien" value
 * @method csdl_tacpham setTacphamtieubieu() Sets the current record's "tacphamtieubieu" value
 * @method csdl_tacpham setFiledownload()    Sets the current record's "filedownload" value
 * @method csdl_tacpham setNgayxuatban()     Sets the current record's "ngayxuatban" value
 * @method csdl_tacpham setTacgiaId()        Sets the current record's "tacgia_id" value
 * @method csdl_tacpham setTacgia()          Sets the current record's "tacgia" value
 * @method csdl_tacpham setChudeId()         Sets the current record's "chude_id" value
 * @method csdl_tacpham setStatus()          Sets the current record's "status" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_tacpham extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_tacpham');
        $this->hasColumn('hoivien_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'ma hoi vien',
             'length' => 5,
             ));
        $this->hasColumn('tentacpham', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten tac pham',
             'length' => 255,
             ));
        $this->hasColumn('gioithieu', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'gioi thieu',
             'length' => 1000,
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));
        $this->hasColumn('tacphamtieubieu', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'tac pham tieu bieu',
             ));
        $this->hasColumn('filedownload', 'string', 255, array(
             'type' => 'string',
             'comment' => 'file download: zip, pdf, doc, docx, xls, xlsx',
             'length' => 255,
             ));
        $this->hasColumn('ngayxuatban', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay xuat ban',
             'length' => 25,
             ));
        $this->hasColumn('tacgia_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Ma Tac gia',
             'length' => 5,
             ));
        $this->hasColumn('tacgia', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tên tác giả',
             'length' => 255,
             ));
        $this->hasColumn('chude_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'ma chu de',
             'length' => 5,
             ));
        $this->hasColumn('status', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Trạng thái(0: Nháp, 1: gửi duyệt, 2: Phê duyệt)',
             'length' => 5,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}