<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_nhatky', 'slave');

/**
 * Basecsdl_nhatky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hoivien_id
 * @property string $tieude
 * @property string $machucnang
 * @property string $module
 * @property timestamp $ngaytao
 * @property string $ip
 * 
 * @method integer     getHoivienId()  Returns the current record's "hoivien_id" value
 * @method string      getTieude()     Returns the current record's "tieude" value
 * @method string      getMachucnang() Returns the current record's "machucnang" value
 * @method string      getModule()     Returns the current record's "module" value
 * @method timestamp   getNgaytao()    Returns the current record's "ngaytao" value
 * @method string      getIp()         Returns the current record's "ip" value
 * @method csdl_nhatky setHoivienId()  Sets the current record's "hoivien_id" value
 * @method csdl_nhatky setTieude()     Sets the current record's "tieude" value
 * @method csdl_nhatky setMachucnang() Sets the current record's "machucnang" value
 * @method csdl_nhatky setModule()     Sets the current record's "module" value
 * @method csdl_nhatky setNgaytao()    Sets the current record's "ngaytao" value
 * @method csdl_nhatky setIp()         Sets the current record's "ip" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_nhatky extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_nhatky');
        $this->hasColumn('hoivien_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'ma hoi vien',
             'length' => 5,
             ));
        $this->hasColumn('tieude', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tieu de',
             'length' => 255,
             ));
        $this->hasColumn('machucnang', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Mã chức năng',
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Phân hệ chức năng',
             'length' => 255,
             ));
        $this->hasColumn('ngaytao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay tao',
             'length' => 25,
             ));
        $this->hasColumn('ip', 'string', 25, array(
             'type' => 'string',
             'comment' => 'địa chỉ ip tác động',
             'length' => 25,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}