<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_thehoivien', 'slave');

/**
 * Basecsdl_thehoivien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hoivien_id
 * @property string $mathe
 * @property string $anhdaidien
 * @property timestamp $ngaycap
 * @property timestamp $ngayhethan
 * @property string $nguoiky
 * @property timestamp $ngayky
 * @property boolean $trangthai
 * 
 * @method integer         getHoivienId()  Returns the current record's "hoivien_id" value
 * @method string          getMathe()      Returns the current record's "mathe" value
 * @method string          getAnhdaidien() Returns the current record's "anhdaidien" value
 * @method timestamp       getNgaycap()    Returns the current record's "ngaycap" value
 * @method timestamp       getNgayhethan() Returns the current record's "ngayhethan" value
 * @method string          getNguoiky()    Returns the current record's "nguoiky" value
 * @method timestamp       getNgayky()     Returns the current record's "ngayky" value
 * @method boolean         getTrangthai()  Returns the current record's "trangthai" value
 * @method csdl_thehoivien setHoivienId()  Sets the current record's "hoivien_id" value
 * @method csdl_thehoivien setMathe()      Sets the current record's "mathe" value
 * @method csdl_thehoivien setAnhdaidien() Sets the current record's "anhdaidien" value
 * @method csdl_thehoivien setNgaycap()    Sets the current record's "ngaycap" value
 * @method csdl_thehoivien setNgayhethan() Sets the current record's "ngayhethan" value
 * @method csdl_thehoivien setNguoiky()    Sets the current record's "nguoiky" value
 * @method csdl_thehoivien setNgayky()     Sets the current record's "ngayky" value
 * @method csdl_thehoivien setTrangthai()  Sets the current record's "trangthai" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_thehoivien extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_the_hoivien');
        $this->hasColumn('hoivien_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'ma hoi vien',
             'length' => 5,
             ));
        $this->hasColumn('mathe', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma the',
             'length' => 25,
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));
        $this->hasColumn('ngaycap', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay cap the hoi vien',
             'length' => 25,
             ));
        $this->hasColumn('ngayhethan', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay het han cua the',
             'length' => 25,
             ));
        $this->hasColumn('nguoiky', 'string', 150, array(
             'type' => 'string',
             'comment' => 'Nguoi ky',
             'length' => 150,
             ));
        $this->hasColumn('ngayky', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay ky',
             'length' => 25,
             ));
        $this->hasColumn('trangthai', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trang thai',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}