<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_dmnghenghiep', 'slave');

/**
 * Basecsdl_dmnghenghiep
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tendanhmuc
 * @property string $gioithieu
 * @property string $anhdaidien
 * @property integer $thutu
 * @property integer $trangthai
 * 
 * @method string            getTendanhmuc() Returns the current record's "tendanhmuc" value
 * @method string            getGioithieu()  Returns the current record's "gioithieu" value
 * @method string            getAnhdaidien() Returns the current record's "anhdaidien" value
 * @method integer           getThutu()      Returns the current record's "thutu" value
 * @method integer           getTrangthai()  Returns the current record's "trangthai" value
 * @method csdl_dmnghenghiep setTendanhmuc() Sets the current record's "tendanhmuc" value
 * @method csdl_dmnghenghiep setGioithieu()  Sets the current record's "gioithieu" value
 * @method csdl_dmnghenghiep setAnhdaidien() Sets the current record's "anhdaidien" value
 * @method csdl_dmnghenghiep setThutu()      Sets the current record's "thutu" value
 * @method csdl_dmnghenghiep setTrangthai()  Sets the current record's "trangthai" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_dmnghenghiep extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_dm_nghenghiep');
        $this->hasColumn('tendanhmuc', 'string', 255, array(
             'type' => 'string',
             'comment' => 'ten danh muc',
             'length' => 255,
             ));
        $this->hasColumn('gioithieu', 'string', 500, array(
             'type' => 'string',
             'comment' => 'Gioi thieu',
             'length' => 500,
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));
        $this->hasColumn('thutu', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Thu tu hien thi',
             'length' => 5,
             ));
        $this->hasColumn('trangthai', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'trang thai',
             'length' => 5,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}