<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_dantoc', 'slave');

/**
 * Basecsdl_dantoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $madantoc
 * @property string $tendantoc
 * @property string $gioithieu
 * @property string $anhdaidien
 * 
 * @method string      getMadantoc()   Returns the current record's "madantoc" value
 * @method string      getTendantoc()  Returns the current record's "tendantoc" value
 * @method string      getGioithieu()  Returns the current record's "gioithieu" value
 * @method string      getAnhdaidien() Returns the current record's "anhdaidien" value
 * @method csdl_dantoc setMadantoc()   Sets the current record's "madantoc" value
 * @method csdl_dantoc setTendantoc()  Sets the current record's "tendantoc" value
 * @method csdl_dantoc setGioithieu()  Sets the current record's "gioithieu" value
 * @method csdl_dantoc setAnhdaidien() Sets the current record's "anhdaidien" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_dantoc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_dantoc');
        $this->hasColumn('madantoc', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma dan toc',
             'length' => 25,
             ));
        $this->hasColumn('tendantoc', 'string', 255, array(
             'type' => 'string',
             'comment' => 'ten dan toc',
             'length' => 255,
             ));
        $this->hasColumn('gioithieu', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'Gioi thieu ve dan toc',
             'length' => 1000,
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}