<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_vanbanphapquy', 'slave');

/**
 * Basecsdl_vanbanphapquy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $matailieu
 * @property string $kyhieu
 * @property string $sotailieu
 * @property timestamp $ngaybanhanh
 * @property timestamp $ngayhieuluc
 * @property timestamp $ngayhethieuluc
 * @property string $tentailieu
 * @property string $trichdan
 * @property string $anhdaidien
 * @property string $filedownload
 * @property boolean $trangthai
 * @property integer $loaivanban_id
 * @property csdl_loaivanban $loai_vbpq
 * 
 * @method string             getMatailieu()      Returns the current record's "matailieu" value
 * @method string             getKyhieu()         Returns the current record's "kyhieu" value
 * @method string             getSotailieu()      Returns the current record's "sotailieu" value
 * @method timestamp          getNgaybanhanh()    Returns the current record's "ngaybanhanh" value
 * @method timestamp          getNgayhieuluc()    Returns the current record's "ngayhieuluc" value
 * @method timestamp          getNgayhethieuluc() Returns the current record's "ngayhethieuluc" value
 * @method string             getTentailieu()     Returns the current record's "tentailieu" value
 * @method string             getTrichdan()       Returns the current record's "trichdan" value
 * @method string             getAnhdaidien()     Returns the current record's "anhdaidien" value
 * @method string             getFiledownload()   Returns the current record's "filedownload" value
 * @method boolean            getTrangthai()      Returns the current record's "trangthai" value
 * @method integer            getLoaivanbanId()   Returns the current record's "loaivanban_id" value
 * @method csdl_loaivanban    getLoaiVbpq()       Returns the current record's "loai_vbpq" value
 * @method csdl_vanbanphapquy setMatailieu()      Sets the current record's "matailieu" value
 * @method csdl_vanbanphapquy setKyhieu()         Sets the current record's "kyhieu" value
 * @method csdl_vanbanphapquy setSotailieu()      Sets the current record's "sotailieu" value
 * @method csdl_vanbanphapquy setNgaybanhanh()    Sets the current record's "ngaybanhanh" value
 * @method csdl_vanbanphapquy setNgayhieuluc()    Sets the current record's "ngayhieuluc" value
 * @method csdl_vanbanphapquy setNgayhethieuluc() Sets the current record's "ngayhethieuluc" value
 * @method csdl_vanbanphapquy setTentailieu()     Sets the current record's "tentailieu" value
 * @method csdl_vanbanphapquy setTrichdan()       Sets the current record's "trichdan" value
 * @method csdl_vanbanphapquy setAnhdaidien()     Sets the current record's "anhdaidien" value
 * @method csdl_vanbanphapquy setFiledownload()   Sets the current record's "filedownload" value
 * @method csdl_vanbanphapquy setTrangthai()      Sets the current record's "trangthai" value
 * @method csdl_vanbanphapquy setLoaivanbanId()   Sets the current record's "loaivanban_id" value
 * @method csdl_vanbanphapquy setLoaiVbpq()       Sets the current record's "loai_vbpq" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_vanbanphapquy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_vanban_phapquy');
        $this->hasColumn('matailieu', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma tai lieu',
             'length' => 25,
             ));
        $this->hasColumn('kyhieu', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ky hieu',
             'length' => 25,
             ));
        $this->hasColumn('sotailieu', 'string', 25, array(
             'type' => 'string',
             'comment' => 'so tai lieu',
             'length' => 25,
             ));
        $this->hasColumn('ngaybanhanh', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Ngày ban hành',
             'length' => 25,
             ));
        $this->hasColumn('ngayhieuluc', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Ngày hiệu lực',
             'length' => 25,
             ));
        $this->hasColumn('ngayhethieuluc', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Ngày hết hiệu lực',
             'length' => 25,
             ));
        $this->hasColumn('tentailieu', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten tai lieu',
             'length' => 255,
             ));
        $this->hasColumn('trichdan', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'Trich dan',
             'length' => 1000,
             ));
        $this->hasColumn('anhdaidien', 'string', 255, array(
             'type' => 'string',
             'comment' => 'hinh anh',
             'length' => 255,
             ));
        $this->hasColumn('filedownload', 'string', 255, array(
             'type' => 'string',
             'comment' => 'file download',
             'length' => 255,
             ));
        $this->hasColumn('trangthai', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trang thai',
             ));
        $this->hasColumn('loaivanban_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Loai van ban phap quy',
             'length' => 5,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('csdl_loaivanban as loai_vbpq', array(
             'local' => 'loaivanban_id',
             'foreign' => 'id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}