<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_danhba', 'slave');

/**
 * Basecsdl_danhba
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $hoten
 * @property timestamp $ngaysinh
 * @property string $gioitinh
 * @property string $diachi
 * @property string $dienthoai
 * @property string $email
 * @property string $donvi
 * 
 * @method string      getHoten()     Returns the current record's "hoten" value
 * @method timestamp   getNgaysinh()  Returns the current record's "ngaysinh" value
 * @method string      getGioitinh()  Returns the current record's "gioitinh" value
 * @method string      getDiachi()    Returns the current record's "diachi" value
 * @method string      getDienthoai() Returns the current record's "dienthoai" value
 * @method string      getEmail()     Returns the current record's "email" value
 * @method string      getDonvi()     Returns the current record's "donvi" value
 * @method csdl_danhba setHoten()     Sets the current record's "hoten" value
 * @method csdl_danhba setNgaysinh()  Sets the current record's "ngaysinh" value
 * @method csdl_danhba setGioitinh()  Sets the current record's "gioitinh" value
 * @method csdl_danhba setDiachi()    Sets the current record's "diachi" value
 * @method csdl_danhba setDienthoai() Sets the current record's "dienthoai" value
 * @method csdl_danhba setEmail()     Sets the current record's "email" value
 * @method csdl_danhba setDonvi()     Sets the current record's "donvi" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_danhba extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_danhba');
        $this->hasColumn('hoten', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Họ và tên',
             'length' => 255,
             ));
        $this->hasColumn('ngaysinh', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'ngay sinh',
             'length' => 25,
             ));
        $this->hasColumn('gioitinh', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Gioi tinh',
             'length' => 25,
             ));
        $this->hasColumn('diachi', 'string', 255, array(
             'type' => 'string',
             'comment' => 'dịa chỉ',
             'length' => 255,
             ));
        $this->hasColumn('dienthoai', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Dien thoai',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Email',
             'length' => 255,
             ));
        $this->hasColumn('donvi', 'string', 255, array(
             'type' => 'string',
             'comment' => 'don vi cong tac',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}