<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('csdl_area', 'slave');

/**
 * Basecsdl_area
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $PROVINCE
 * @property string $DISTRICT
 * @property string $PRECINCT
 * @property string $STREET_BLOCK
 * @property string $STREET
 * @property string $NAME
 * @property string $FULL_NAME
 * @property integer $STATUS
 * 
 * @method string    getPROVINCE()     Returns the current record's "PROVINCE" value
 * @method string    getDISTRICT()     Returns the current record's "DISTRICT" value
 * @method string    getPRECINCT()     Returns the current record's "PRECINCT" value
 * @method string    getSTREETBLOCK()  Returns the current record's "STREET_BLOCK" value
 * @method string    getSTREET()       Returns the current record's "STREET" value
 * @method string    getNAME()         Returns the current record's "NAME" value
 * @method string    getFULLNAME()     Returns the current record's "FULL_NAME" value
 * @method integer   getSTATUS()       Returns the current record's "STATUS" value
 * @method csdl_area setPROVINCE()     Sets the current record's "PROVINCE" value
 * @method csdl_area setDISTRICT()     Sets the current record's "DISTRICT" value
 * @method csdl_area setPRECINCT()     Sets the current record's "PRECINCT" value
 * @method csdl_area setSTREETBLOCK()  Sets the current record's "STREET_BLOCK" value
 * @method csdl_area setSTREET()       Sets the current record's "STREET" value
 * @method csdl_area setNAME()         Sets the current record's "NAME" value
 * @method csdl_area setFULLNAME()     Sets the current record's "FULL_NAME" value
 * @method csdl_area setSTATUS()       Sets the current record's "STATUS" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecsdl_area extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('csdl_area');
        $this->hasColumn('PROVINCE', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma tinh',
             'length' => 25,
             ));
        $this->hasColumn('DISTRICT', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma huyen',
             'length' => 25,
             ));
        $this->hasColumn('PRECINCT', 'string', 25, array(
             'type' => 'string',
             'comment' => 'Ma phuong,xa',
             'length' => 25,
             ));
        $this->hasColumn('STREET_BLOCK', 'string', 255, array(
             'type' => 'string',
             'comment' => 'khu pho',
             'length' => 255,
             ));
        $this->hasColumn('STREET', 'string', 255, array(
             'type' => 'string',
             'comment' => 'duong pho',
             'length' => 255,
             ));
        $this->hasColumn('NAME', 'string', 255, array(
             'type' => 'string',
             'comment' => 'ten don vi',
             'length' => 255,
             ));
        $this->hasColumn('FULL_NAME', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Ten day du',
             'length' => 255,
             ));
        $this->hasColumn('STATUS', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'trang thai',
             'length' => 5,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}