all:
  # Change these if you'd like to move/modify CSS & JS files
  tmcTwitterBootstrapPlugin:
    bootstrap_path:              /tmcTwitterBootstrapPlugin/css/bootstrap.min.css
    responsive_bootstrap_path:   /tmcTwitterBootstrapPlugin/css/bootstrap-responsive.min.css
    admin_styles_path:           /tmcTwitterBootstrapPlugin/css/styles.css
    jquery_path:                 /tmcTwitterBootstrapPlugin/js/jquery.min.js
    bootstrap_js_path:           /tmcTwitterBootstrapPlugin/js/bootstrap.min.js
    admin_js_path:               /tmcTwitterBootstrapPlugin/js/global.js

#    # The route/URI to use for the nav bar's "brand" link
#    profile_route: @homepage?username=
#    # The link next for the nav bar's "brand" link
#    dashboard_name: Administration
    header:
      menu:
        Phân hệ Tin tức:
          credentials: [[admin,news_editor,news_approved,news_public]]
          dropdown:
            Quản lý tin đợi duyệt:
              credentials: [[admin,news_editor,news_approved,news_public]]
              route: ad_article
              icon: text.png
            Quản lý tin đợi đăng:
              credentials: [[admin,news_editor,news_approved,news_public]]
              route: ad_article_adArticlesAproved
              icon: text.png
            Quản lý tin đã đăng:
              credentials: [[admin,news_editor,news_approved,news_public]]
              route: ad_article_adArticlesPublish
              icon: text.png
        Phân hệ khác:
          credentials: [[admin,subAdmin]]
          dropdown:
            Quản lý chuyên mục:
              credentials: [[admin]]
              route: ad_category
              icon: squares36.png
            Trang liên hệ:
              credentials: [[admin]]
              route: ad_contact
              icon: business133.png
            Quản lý video:
              credentials: [[admin,subAdmin]]
              route: ad_video
              icon: movie36.png
            Quản lý album:
              credentials: [[admin,subAdmin]]
              route: ad_album
              icon: pictures1.png
            Quản lý chuyên mục văn bản:
              credentials: [[admin]]
              route: ad_document_category
              icon: squares36.png
            Quản lý văn bản:
              credentials: [[admin]]
              route: ad_document
              icon: books8.png
            Quản lý nội dung:
              credentials: [[admin,subAdmin]]
              route: ad_html
              icon: text.png
            Quản lý thông tin phản hồi:
              credentials: [[admin]]
              route: ad_comment
              icon: text.png
            Danh sách hội viên:
              credentials: [[admin]]
              route: ad_personal
              icon: users6.png
            Vị trí quảng cáo:
              credentials: [[admin,subAdmin]]
              route: ad_advertise_location
              icon: computer.png
            Quản lý Banner - quảng cáo:
              credentials: [[admin,subAdmin]]
              route: ad_advertise
              icon: computer.png
            Quản lý liên kết:
              credentials: [[admin]]
              route: ad_link
              icon: link71.png
        Quản trị hệ thống:
          credentials: [admin]
          dropdown:
            Danh sách người dùng:
              route: sf_guard_user
              icon: users6.png
            Danh sách quyền hạn:
              route: sf_guard_permission
              icon: users6.png
            Thống kê bài viết trong chuyên mục:
              route: ad_report_total_record
              icon: file148.png
            Thống kê lượt xem bài trong chuyên mục:
              route: ad_report_hicounter
              icon: pie-chart9.png

  sf_captchagd:
     image_width:                180 # image width in pixels
     image_height:               27 # image height in pixels
     chars:                      "123456789abcdefghijklmnopqrstuvwxyz" # possible chars in captcha
     length:                     2 # length of captcha
     font_size:                  14 # font size
     force_new_captcha:          true # if true - captcha regenerated EVERY request, even if user input true value before
     fonts: ["akbar/vavobi.ttf"]