ad_contact:
  class: sfDoctrineRouteCollection
  options:
    model:                AdContact
    module:               adManageContact
    prefix_path:          /adManageContact
    column:               id
    with_wildcard_routes: true

ad_article_adArticlesPublish:
  class: sfDoctrineRouteCollection
  options:
    model:                AdArticle
    module:               adArticlesPublish
    prefix_path:          /adArticlesPublish
    column:               id
    with_wildcard_routes: true

ad_article_adArticlesAproved:
  class: sfDoctrineRouteCollection
  options:
    model:                AdArticle
    module:               adArticlesAproved
    prefix_path:          /adArticlesAproved
    column:               id
    with_wildcard_routes: true

ad_article:
  class: sfDoctrineRouteCollection
  options:
    model:                AdArticle
    module:               adArticlesEditor
    prefix_path:          /adArticlesEditor
    column:               id
    with_wildcard_routes: true

ad_category:
  class: sfDoctrineRouteCollection
  options:
    model:                AdCategory
    module:               adManageCategory
    prefix_path:          /adManageCategory
    column:               id
    with_wildcard_routes: true

sf_guard_change_password:
  url:   /guard/change_password
  param: { module: sfGuardAuth, action: changePassword }

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /sfGuardGroup
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /sfGuardUser
    column:               id
    with_wildcard_routes: true
 
sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /sfGuardPermission
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: homePage, action: index }
# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
