ad_document:
  class: sfDoctrineRouteCollection
  options:
    model:                AdDocument
    module:               adDocument
    prefix_path:          /adDocument
    column:               id
    with_wildcard_routes: true

ad_document_category:
  class: sfDoctrineRouteCollection
  options:
    model:                AdDocumentCategory
    module:               adDocumentCategory
    prefix_path:          /adDocumentCategory
    column:               id
    with_wildcard_routes: true
ad_personal_import:
  url:   /adManagePersonal/import
  param: { module: adManagePersonal, action: import }
ad_comment:
  class: sfDoctrineRouteCollection
  options:
    model:                AdComment
    module:               adManageComment
    prefix_path:          /adManageComment
    column:               id
    with_wildcard_routes: true

ad_advertise_image:
  class: sfDoctrineRouteCollection
  options:
    model:                AdAdvertiseImage
    module:               adManageAdvertiseImage
    prefix_path:          /adManageAdvertiseImage
    column:               id
    with_wildcard_routes: true

ad_advertise:
  class: sfDoctrineRouteCollection
  options:
    model:                AdAdvertise
    module:               adManageAdvertise
    prefix_path:          /adManageAdvertise
    column:               id
    with_wildcard_routes: true

ad_advertise_location:
  class: sfDoctrineRouteCollection
  options:
    model:                AdAdvertiseLocation
    module:               adManageLocation
    prefix_path:          /adManageLocation
    column:               id
    with_wildcard_routes: true

ad_personal:
  class: sfDoctrineRouteCollection
  options:
    model:                AdPersonal
    module:               adManagePersonal
    prefix_path:          /adManagePersonal
    column:               id
    with_wildcard_routes: true

ad_html:
  class: sfDoctrineRouteCollection
  options:
    model:                AdHtml
    module:               adManageHtml
    prefix_path:          /adManageHtml
    column:               id
    with_wildcard_routes: true


ad_contact:
  class: sfDoctrineRouteCollection
  options:
    model:                AdContact
    module:               adManageContact
    prefix_path:          /adManageContact
    column:               id
    with_wildcard_routes: true

ad_article_adArticlesPublish:
  class: sfDoctrineRouteCollection
  options:
    model:                AdArticle
    module:               adArticlesPublish
    prefix_path:          /adArticlesPublish
    column:               id
    with_wildcard_routes: true

ad_article_adArticlesAproved:
  class: sfDoctrineRouteCollection
  options:
    model:                AdArticle
    module:               adArticlesAproved
    prefix_path:          /adArticlesAproved
    column:               id
    with_wildcard_routes: true

ad_article:
  class: sfDoctrineRouteCollection
  options:
    model:                AdArticle
    module:               adArticlesEditor
    prefix_path:          /adArticlesEditor
    column:               id
    with_wildcard_routes: true

ad_photo:
  class: sfDoctrineRouteCollection
  options:
    model:                AdPhoto
    module:               adPhoto
    prefix_path:          /adPhoto
    column:               id
    with_wildcard_routes: true

ad_album:
  class: sfDoctrineRouteCollection
  options:
    model:                AdAlbum
    module:               adAlbum
    prefix_path:          /adAlbum
    column:               id
    with_wildcard_routes: true


ad_video:
  class: sfDoctrineRouteCollection
  options:
    model:                AdVideo
    module:               adVideo
    prefix_path:          /adVideo
    column:               id
    with_wildcard_routes: true
ad_category:
  class: sfDoctrineRouteCollection
  options:
    model:                AdCategory
    module:               adManageCategory
    prefix_path:          /adManageCategory
    column:               id
    with_wildcard_routes: true

sf_guard_change_password:
  url:   /guard/change_password
  param: { module: sfGuardAuth, action: changePassword }

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /sfGuardGroup
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /sfGuardUser
    column:               id
    with_wildcard_routes: true
 
sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /sfGuardPermission
    column:               id
    with_wildcard_routes: true

vtp_search_ajax_loadarticle:
  url:   /ajax/LoadArticle
  param: { module: ajax, action: loadArticle }

# default rules
homepage:
  url:   /
  param: { module: homePage, action: index }
# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
