<?php

/**
 * AdAdvertiseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdAdvertiseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdAdvertiseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdAdvertise');
    }
}