<?php

/**
 * AdAdvertiseImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdAdvertiseImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdAdvertiseImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdAdvertiseImage');
    }
}