<?php

/**
 * AdAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdAlbum');
    }
}