<?php

/**
 * AdAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdAlbum');
    }

    public static function getALbumById($id){
        $q=AdAlbumTable::getInstance()->createQuery()
            ->where('id=?',$id);
        return $q->fetchOne();
    }
    public static function checkSlug($slug,$id)
    {
        $query=  AdAlbumTable::getInstance()->createQuery()
            ->select('slug')
            ->where('slug=?',$slug)
            ->andWhere('id<>?',$id);
        return $query;
    }

    //cap nhat gia tri defaul
    public static function updateDefault($id){
        $query = AdAlbumTable::getInstance()->createQuery()
            ->update()
            ->set('is_default','?',  VtCommonEnum::NUMBER_ZERO)
            ->where('id<>?',$id);
        $query->execute();
    }
}