<?php

/**
 * AdArticlesRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdArticlesRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdArticlesRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdArticlesRelated');
    }
}