<?php

/**
 * AdArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdArticle');
    }
}