<?php

/**
 * AdCategoryPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdCategoryPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdCategoryPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdCategoryPermission');
    }
}