<?php

/**
 * AdCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdCategory');
    }
}