<?php

/**
 * AdDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDocument');
    }

    //lay danh sach tai lieu theo chuyen muc
    public static function getDocumentByCatId($catId, $limit=null){
        $query = AdDocumentTable::getInstance()->createQuery()
            ->where('category_id =? ',$catId)
            ->andWhere('is_active=?', VtCommonEnum::NUMBER_ONE)
            ->andWhere('is_home=?',VtCommonEnum::NUMBER_ONE);
        if($limit){
            $query->limit($limit);
        }
        return $query;
    }
}