<?php

/**
 * AdDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDocument');
    }
}