<?php

/**
 * AdDocumentCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDocumentCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDocumentCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDocumentCategory');
    }

    public static function getCategoryDocumentById($id){
        $query = AdDocumentCategoryTable::getInstance()->createQuery()
            ->Where('id=?', $id);
        return $query->fetchOne();
    }
}