<?php

/**
 * AdHtmlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdHtmlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdHtmlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdHtml');
    }
}