<?php

/**
 * AdPersonalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdPersonalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdPersonalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdPersonal');
    }
}