<?php

/**
 * AdPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdPhoto');
    }
}