<?php

/**
 * AdReportTotalRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdReportTotalRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdReportTotalRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdReportTotalRecord');
    }
}