<?php

/**
 * AdReportHicounterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdReportHicounterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdReportHicounterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdReportHicounter');
    }
}