<?php

/**
 * AdUsersLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdUsersLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdUsersLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdUsersLog');
    }
}