<?php

/**
 * AdUserSigninLockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdUserSigninLockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdUserSigninLockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdUserSigninLock');
    }
}