<?php

/**
 * AdVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdVideo');
    }
}