<?php

/**
 * AdVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdVideo');
    }
    public static function checkSlug($slug,$id)
    {
        $query=  AdVideoTable::getInstance()->createQuery()
            ->select('slug')
            ->where('slug=?',$slug)
            ->andWhere('id<>?',$id);
        return $query;
    }

    public static function updateDefault()
    {
        $query=AdVideoTable::getInstance()->createQuery()
            ->update()
            ->set('is_default', '?', VtCommonEnum::NUMBER_ZERO)
            ->where('is_default=?',VtCommonEnum::NUMBER_ONE);
        return $query->execute();
    }
}