<?php

/**
 * csdl_thehoivienTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_thehoivienTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_thehoivienTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_thehoivien');
    }
    public static function getTheHoiVien($hoiVienId)
    {
        return csdl_thehoivienTable::getInstance()->createQuery()
            ->where('hoivien_id =?',$hoiVienId);
    }
}