<?php

/**
 * csdl_tacphamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_tacphamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_tacphamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_tacpham');
    }

    public static function getListTacpham($limit=6){
        return csdl_tacphamTable::getInstance()->createQuery()
            ->select('tentacpham, gioithieu, anhdaidien, ngayxuatban, chude_id, tacgia_id')
            ->where('status=2')
            ->orderby('updated_at')
            ->limit($limit)
            ->execute();
    }

    public static function getListTacphamReturnArray($limit=6){
        return csdl_tacphamTable::getInstance()->createQuery('c')
            ->select('c.id ,c.tentacpham, c.gioithieu , c.anhdaidien, c.ngayxuatban,tg.hoten, cd.tenchude')
            ->leftjoin('c.csdlTacgia tg')
            ->leftjoin('c.csdlChude cd')
            ->where('status=2')
            //->orderby('c.updated_at desc')
            ->limit($limit)
            ->fetchArray();
    }

    public static function getTacphamById($id){
        return csdl_tacphamTable::getInstance()->createQuery('c')
            ->select('c.id ,c.tentacpham, c.gioithieu , c.anhdaidien, c.filedownload, c.ngayxuatban,tg.hoten, cd.tenchude')
            ->leftjoin('c.csdlTacgia tg')
            ->leftjoin('c.csdlChude cd')
            ->where('status=2')
            ->andWhere('c.id=?',$id)
            ->fetchArray();
    }

    //lay danh sach tac pham heo hoi vien
    public static function getTacphamByHoiVienId($id){
        return csdl_tacphamTable::getInstance()->createQuery('c')
            ->select('c.id ,c.tentacpham, c.gioithieu , c.anhdaidien, c.filedownload, c.ngayxuatban,tg.hoten, cd.tenchude')
            ->leftjoin('c.csdlTacgia tg')
            ->leftjoin('c.csdlChude cd')
            ->where('status=2')
            ->andWhere('c.hoivien_id=?',$id)
            ->fetchArray();
    }
}