<?php

/**
 * csdl_vanbanphapquyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_vanbanphapquyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_vanbanphapquyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_vanbanphapquy');
    }

    public static function getVanBan($limit)
    {
        return csdl_vanbanphapquyTable::getInstance()->createQuery()
            ->orderBy('updated_at desc')
            ->limit($limit);
    }

    public static function getVanBanDetail($id)
    {
        return csdl_vanbanphapquyTable::getInstance()->createQuery()
            ->where('id =?',$id)
            ->andWhere('trangthai =?',VtCommonEnum::NUMBER_ONE);
    }
}