<?php

/**
 * csdl_lylichhoivienTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_lylichhoivienTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_lylichhoivienTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_lylichhoivien');
    }

    public static function getNewUser($limit)
    {
        return csdl_lylichhoivienTable::getInstance()->createQuery()
            ->where('hoivien_id>0')
            ->orderBy('updated_at desc')
            ->limit($limit);
    }

    public static function getUserDetail($hoiVienId)
    {
        return csdl_lylichhoivienTable::getInstance()->createQuery()
            ->where('hoivien_id =?',$hoiVienId);
    }

    public static function dsHoivienForThe(){
    return csdl_lylichhoivienTable::getInstance()->createQuery()
        ->select('hoivien_id, hodem ,ten ')
        ->where('hoivien_id>0')
        ->orderBy('ten asc')
        ->fetchArray();
}

    public static function hotenHoivien($hoivienId){
        $result= csdl_lylichhoivienTable::getInstance()->createQuery()
            ->select('hodem, ten')
            ->where('hoivien_id=?',$hoivienId)
            ->fetchArray();
        if(count($result)>0){
            return $result[0]['hodem'];
        }
        return '';
    }

    //lay danh sach hoi vien active

}