<?php

/**
 * csdl_coquanbanhanhTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_coquanbanhanhTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_coquanbanhanhTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_coquanbanhanh');
    }
}