<?php

/**
 * csdl_tacpham
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class csdl_tacpham extends Basecsdl_tacpham
{
    public function setUp()
    {
        $this->hasMany('csdl_tacgia as csdlTacgia', array(
            'local' => 'tacgia_id',
            'foreign' => 'id'));
        $this->hasMany('csdl_chude as csdlChude', array(
            'local' => 'chude_id',
            'foreign' => 'id'));
        parent::setUp();
    }
}