<?php

/**
 * csdl_areaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_areaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_areaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_area');
    }
}