<?php

/**
 * csdl_areaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_areaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_areaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_area');
    }
    //Lay danh sach tinh thanh pho
    public static function getCity(){
        $query=  csdl_areaTable::getInstance()->createQuery()
            ->where("DISTRICT = '' AND PRECINCT = '' AND STATUS = 1");
        return $query;
    }

    public static function getProvinceByCityCode($cityCode){
        $query=  csdl_areaTable::getInstance()->createQuery()
            ->where("PROVINCE =? ", $cityCode)
            ->andWhere("DISTRICT <> '' AND PRECINCT = '' AND STATUS = 1");
        return $query;
    }

    public static function getProvinceKey(){
        $query=  csdl_areaTable::getInstance()->createQuery()
            ->where("DISTRICT <> '' AND PRECINCT = '' AND STATUS = 1");
        return $query;
    }
}