<?php

/**
 * csdl_tailieunghiepvuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_tailieunghiepvuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_tailieunghiepvuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_tailieunghiepvu');
    }
}