<?php

/**
 * csdl_nhatkyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_nhatkyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_nhatkyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_nhatky');
    }
}