<?php

/**
 * csdl_danhbaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_danhbaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_danhbaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_danhba');
    }
}