<?php

/**
 * csdl_loaigiaithuongTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_loaigiaithuongTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_loaigiaithuongTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_loaigiaithuong');
    }
}