<?php

/**
 * csdl_coquanbaochiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_coquanbaochiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_coquanbaochiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_coquanbaochi');
    }

    public static function dsCoquan(){
        $query=  csdl_coquanbaochiTable::getInstance()->createQuery()
//            ->andWhere('trangthai = ',VtCommonEnum::NUMBER_ONE);
        ->orderBy('tendonvi');
        return $query;
    }

    public static function tenDonvi($Id){
        $result= csdl_coquanbaochiTable::getInstance()->createQuery()
            ->select('tendonvi')
            ->where('id=?',$Id)
            ->fetchArray();
        if(count($result)>0){
            return $result[0]['tendonvi'];
        }
        return '';
    }
}