<?php

/**
 * csdl_chinhtriTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_chinhtriTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_chinhtriTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_chinhtri');
    }


    public static function getListChinhtri(){
        $q=csdl_chinhtriTable::getInstance()->createQuery()
            ->select('*')
            ->orderby('name asc');
        return $q->execute();
    }
}