<?php

/**
 * csdl_loaivanbanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_loaivanbanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_loaivanbanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_loaivanban');
    }
}