<?php

/**
 * csdl_tacgiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_tacgiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_tacgiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_tacgia');
    }

    public static function  dsTacgia(){
        $q=csdl_tacgiaTable::getInstance()->createQuery()
            ->select('id, hoten')
            ->orderby('hoten asc');
        return $q->fetchArray();
    }
}