<?php

/**
 * csdl_loaigiaithuong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class csdl_loaigiaithuong extends Basecsdl_loaigiaithuong
{

}