<?php

/**
 * csdl_dmnghenghiepTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_dmnghenghiepTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_dmnghenghiepTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_dmnghenghiep');
    }

    public static function getAllJob()
    {
        return csdl_dmnghenghiepTable::getInstance()->createQuery()
            ->orderBy('thutu desc');
    }
}