<?php

/**
 * csdl_tailieunghiepvuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_tailieunghiepvuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_tailieunghiepvuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_tailieunghiepvu');
    }

    public static function getTaiLieu($limit)
    {
        return csdl_tailieunghiepvuTable::getInstance()->createQuery()
            ->where('trangthai =?',VtCommonEnum::NUMBER_ONE)
            ->andWhere('trangthai =?',VtCommonEnum::NUMBER_ONE)
            ->orderBy('updated_at desc')
            ->limit($limit);
    }

    public static function getTaiLieuDetail($id)
    {
        return csdl_tailieunghiepvuTable::getInstance()->createQuery()
            ->where('id =?',$id)
            ->andWhere('trangthai =?',VtCommonEnum::NUMBER_ONE);
    }
}