<?php

/**
 * csdl_loaitailieuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_loaitailieuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_loaitailieuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_loaitailieu');
    }
}