<?php

/**
 * csdl_lichcongtacTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_lichcongtacTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_lichcongtacTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_lichcongtac');
    }
}