<?php

/**
 * csdl_chudeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_chudeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_chudeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_chude');
    }
}