<?php

/**
 * csdl_vanbanphapquyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class csdl_vanbanphapquyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object csdl_vanbanphapquyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('csdl_vanbanphapquy');
    }
}