<?php

/**
 * sfGuardUserHNBTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserHNBTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserHNBTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserHNB');
    }

    public static function getListPersonal($limit = null, $offset = null){
        return sfGuardUserHNBTable::getInstance()->createQuery('a')
            ->orderBy('a.first_name asc')
            ->fetchArray();
    }


    //frontend
    public static function getListPerson($full_name, $phone_number,$email,$limit)
    {
        $query = sfGuardUserHNBTable::getInstance()->createQuery('s')
            ->select()
            ->innerJoin('s.Groups c')
//            ->where('s.id = c.hoivien_id')
            ->orderBy('s.first_name asc')
            ->limit($limit);

        if($full_name!=""){
            $query->andWhere("s.first_name LIKE ? OR s.last_name LIKE ?", array( "%" . trim($full_name). "%",  "%" . trim($full_name) . "%"));
        }
        if($phone_number!=""){
            $query->andWhere('s.phone=?',$phone_number);
        }
        if($email!=""){
            $query->andWhere('s.email_address=?',$email);
        }
        return $query;
    }
}