all:
  slave:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=hnb_log'
      username: root
      password:
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=hnb'
      username: root
      password:
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
