all:
  slave:
    class: sfDoctrineDatabase
    param:
#      dsn: 'mysql:host=103.237.145.134;dbname=csdl'
#      username: root
#      password: 3n@SFIw1
      dsn: 'mysql:host=localhost;dbname=csdl'
      username: root
      password:
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
  doctrine:
    class: sfDoctrineDatabase
    param:
#      dsn: 'mysql:host=103.237.145.134;dbname=hnb'
#      username: root
#      password: 3n@SFIw1
      dsn: 'mysql:host=localhost;dbname=hnb'
      username: root
      password:
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
  