generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           AdDocumentCategory
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ad_document_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: Tên chuyên mục}
        image_path: {label: Ảnh đại diện}
        description: {label: Mô tả}
        priority: {label: Thứ tự}
      list:
        title: Danh sách chuyên mục văn bản
        display: [name, description, priority]
      filter:
        display: [name]
      form:
        class: AdDocumentCategoryAdminForm
        display: [name, image_path, description, priority]
        fields:
          name: {label: Tên chuyên mục *}
      edit:
        title: Chỉnh sửa chuyên mục văn bản
      new:
        title: Thêm mới chuyên mục văn bản
